# Generated by Django 4.1.7 on 2024-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('party_abbreviation', models.CharField(max_length=10)),
                ('total_votes_polled', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
